src/application.c File Reference
This file consists of all the functions required for Application Thread.
#include `inc/msg_queue.h`
#include `inc/sync_objects.h`
#include `inc/timer.h`
#include `inc/spi.h`
#include `inc/led.h`
#include `inc/nrf_driver.h`
#include `inc/buzzer.h`
#include `inc/keypad.h`
#include `inc/uart_comm_bbg.h`
#include `inc/checksum.h`
#include `inc/myuart.h`
#include `inc/fingerprint.h`
#include `inc/delay.h`
#include `inc/lcd.h`
#include `inc/packet.h`
#include `inc/application.h`
Functions
uint8_t sensortask_init (void)
This function creates a task.
void system_init (void)
This function initializes the system with the required configurations and peripherals.
static void sensorcheck (void *pvParameters)
Detailed Description
This file consists of all the functions required for Application Thread.
The Code has been executed on TIVA C Series TM4C1294XL on FreeRTOS.
Author
Siddhant Jajoo
Date
04/29/2019
Copyright
Copyright (c) 2019
Function Documentation
sensorcheck()
static void sensorcheck (void * pvParameters) [static]
Definition at line 102 of file application.c.
References ACK, delay_ms(), fp_cmdsend(), FP_GETENROLLCOUNT_CMD, fp_interrupt_disable(), fp_interrupt_enable(), fp_led_status(), FP_LEDON, FP_NOPARAM, LCD_write(), LED4, led_off(), led_on(), otp_flag, printf, RESPONSE_SIZE, sensor_check, and UART_FP.
Referenced by sensortask_init().
sensortask_init()
uint8_t sensortask_init (void)
This function creates a task.
Returns
void.
Definition at line 32 of file application.c.
References LEDTASKSTACKSIZE, and sensorcheck().
system_init()
void system_init (void)
This function initializes the system with the required configurations and peripherals.
Returns
void.
Definition at line 45 of file application.c.
References BAUDRATE_FP, buzzer_config(), buzzer_dutycycle(), checksum_init(), CLOCK, ConfigureUART(), configureUART_bbg(), degrade_mode, fp_init(), fp_interrupt_config(), keypad_config(), keypad_interrupt_enable(), lcd_init(), led_init(), MAX_FREQ, mutex_create(), otp_arr, otp_count, otp_flag, OTP_INPUT_TIME, otp_retries, PACKET_RETRY_TIME, queue_create(), sem_create(), sensor_check, timer_config(), timer_otp, timer_retry, uart_configure(), and UART_FP.