inc/application.h File Reference
Header file for application.c.
#include `inc/main.h`
Functions
void system_init (void)
This function initializes the system with the required configurations and peripherals.
uint8_t sensortask_init (void)
This function creates a task.
static void sensorcheck (void *pvParameters)
Callback function for sensorcheck task.
Detailed Description
Header file for application.c.
The file consists of all the function declarations, macros and typedefs related to Application Task. The Code has been executed on TIVA C Series TM4C1294XL on FreeRTOS.
Author
Siddhant Jajoo
Date
04/29/2019
Copyright
Copyright (c) 2019
Function Documentation
sensorcheck()
static void sensorcheck (void * pvParameters) [static]
Callback function for sensorcheck task.
Parameters
pvParameters Not in use.
Returns
void.
sensortask_init()
uint8_t sensortask_init (void)
This function creates a task.
Returns
void.
Definition at line 32 of file application.c.
References LEDTASKSTACKSIZE, and sensorcheck().
system_init()
void system_init (void)
This function initializes the system with the required configurations and peripherals.
Returns
void.
Definition at line 45 of file application.c.
References BAUDRATE_FP, buzzer_config(), buzzer_dutycycle(), checksum_init(), CLOCK, ConfigureUART(), configureUART_bbg(), degrade_mode, fp_init(), fp_interrupt_config(), keypad_config(), keypad_interrupt_enable(), lcd_init(), led_init(), MAX_FREQ, mutex_create(), otp_arr, otp_count, otp_flag, OTP_INPUT_TIME, otp_retries, PACKET_RETRY_TIME, queue_create(), sem_create(), sensor_check, timer_config(), timer_otp, timer_retry, uart_configure(), and UART_FP.