inc/delay.h File Reference
Header file for delay functions.
#include `inc/main.h`
Functions
void delay_ms (uint32_t ms)
This function provides the specified amount of delay.
void delay_us (uint32_t us)
This function provides the specified amount of delay.
Detailed Description
Header file for delay functions.
The file consists of all the function declarations, macros and typedefs related to delay functions. The Code has been executed on TIVA C Series TM4C1294XL on FreeRTOS.
Author
Siddhant Jajoo.
Date
04/26/2019
Copyright
Copyright (c) 2019
Function Documentation
delay_ms()
void delay_ms (uint32_t ms) [inline]
This function provides the specified amount of delay.
Parameters
ms Time in milliseconds.
Returns
void.
Definition at line 26 of file delay.h.
References g_ui32SysClock.
Referenced by column_handler(), packet_loopback_test(), sensorcheck(), timer1handler(), and uart_packet_handler().
delay_us()
void delay_us (uint32_t us) [inline]
This function provides the specified amount of delay.
Parameters
us Time in microseconds.
Returns
void.
Definition at line 37 of file delay.h.
References g_ui32SysClock.